### ISSUE TITLE
README.md: Mention new fields

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/menu_node_views#1]
> The module adds new, menu-related filter/sort criteria to those available by views

After testing the release, I noticed that the module also adds the following new fields:

- Menu: Depth
  The depth of the menu item.
- Menu: Description
  The description used for the menu item.
- Menu: Hidden
  The menu item visibility.
- Menu: Link path
  The link path for the menu item.
- Menu: Link title
  The link text used for the menu item.
- Menu: Menu link id
  The unique menu link identifier.
- Menu: Menu name
  The name of the menu.
- Menu: Node id
  The node id, menu-sensitive.
- Menu: Parent
  The top-level parent of the menu item.
- Menu: Parent menu link id
  The unique menu link identifier for this item's parent.
- Menu: Weight
  The weight of the menu item.

**Comment by VasasA** [comment]
@olafgrabienski Thank You! I inserted it into the README.md
https://github.com/backdrop-contrib/menu_node_views/commit/d9916554e0f85e30f8a605f398cfbfa72cb8071d

**Comment by olafgrabienski** [comment]
Thanks!

> If the view shows 'Menu tree', the module adds new fields

What's the meaning of "If the view shows 'Menu tree'"? (I saw the new fields on a standard content view.)

**Comment by VasasA** [comment]
I see the picture below, but this page is configurable. So I fixed the README.md:
`The module adds new fields under appropriate conditions (for example when the view shows 'Menu tree'):`

![kép](https://user-images.githubusercontent.com/8567234/60341307-53c09500-99ae-11e9-9382-91eff50ea5f8.png)

**Comment by olafgrabienski** [comment]
Yes, I forgot indeed that the View has to be configured to show fields. What about something like this:

`When a view is configured to show fields (Format > Show: Fields), the module allows you to add new fields:`

**Comment by VasasA** [comment]
It's perfect. Thank You! I updated the README.md

**Comment by olafgrabienski** [comment]
Great, thank *you*! (Closing.)
