### ISSUE TITLE
README.md: Add Backdrop screenshot

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/menu_node_views#2]
The screenshot provided in README.md is from Drupal. Let's put a screenshot from the Backdrop UI. Here is an example of new fields provided by *Menu Node Views*:

![screen-menu-node-views-add-fields](https://user-images.githubusercontent.com/14188307/60028258-4e5a0680-969f-11e9-990a-8d2c9d2901db.png)

**Comment by VasasA** [comment]
@olafgrabienski Thank You! I replaced the screenshot and improved the README.md
https://github.com/backdrop-contrib/menu_node_views/commit/d9916554e0f85e30f8a605f398cfbfa72cb8071d
 Related: #1

**Comment by olafgrabienski** [comment]
Great, thank you! (Closing the issue.)
