### ISSUE TITLE
Link in Readme points to the module itself

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/menu_node_views#3]
In the README.md, the link in the **Dependencies** section doesn't point to the *Menu Node API* module but to *Menu Node Views* itself.

Instead of

`Use of the module requires that you download and install the [Menu Node API](https://backdropcms.org/project/menu_node_views)`

it should be:

`... (https://backdropcms.org/project/menu_node).`

**Comment by VasasA** [comment]
@olafgrabienski  Thank You! I fixed it and published a new release 1.x.-1.0.1

**Comment by olafgrabienski** [comment]
Thanks, @VasasA !
