### ISSUE TITLE
Filters do not work, if a menu entry is empty (undefined)

### ISSUE THREAD

**Issue by schoenid** [backdrop-contrib/menu_node_views#4]
This is a question or suggestion for an additional feature.

These filters do not work, if a menu entry is empty (undefined).
It would be very helpful, to have a filter for undefined content menus too. 
Often users forget to define one or do not have the permission to add content to a menu.
In other scenarios it's simply not required.

To have the possibility, to create a view for such content, it would be very helpful, to have a filter like "menu: not in content".

Would you like to create one, please?
Thanks a lot in advance.

**Comment by VasasA** [comment]
@schoenid I created a new branch: [no_content_filter](https://github.com/backdrop-contrib/menu_node_views/tree/no_content_filter) This version contains the new "Not in content" filter. Please test this version: [Download](https://github.com/backdrop-contrib/menu_node_views/archive/refs/heads/no_content_filter.zip)

**Comment by schoenid** [comment]
Thank you @VasasA 

Unfortunately it's not working.
Maybe you missunderstood me?

I'm searching for a possibility to filter for "Content without Menu entry". (see point 1. below ...)
So the menu entry of the content is empty, not the menu without content.
As I understand the help for the filter, you designed it for "Menu items without content", which is exactly th contrary.

To compare:
1. a content without menu entry contains in DEVEL: menu_node_links (Array, 0 elements) 
2. a content with a menu entry contains in DEVEL: menu_node_links (Array, 1 element)

So the term "menu: not in content" would maybe better "content: without menu entry"
The meaning I had in sense was: The content has the possibility to have a menu entry defined, but it's empty.

If I use the other menu node views filters, I have the problem, that if a content has no menu, the filter returns nothing, so the result is empty and there is no possibility to invert it, like: NOT(find any content, which has a menu defined inside). There are several possibilities to configure, like "less, equal, greater, between, regexp", but not for "nothing" or "not existing".

So as example, if I use the filter "Menu: Parent (!= 422)", so I configure it, not to use the parent ID 422, which is linked in some content, the **result is empty**, altough, there are many contents, where the expression would be true. There is many content, which parent is not 422, because these do not have any parent. But there is no option, to say, "there is no parent" as an option, to display such content.

By the way: is it OK to ask you for this menu node views filter option, or should I better ask the core developers, to include the "nothing" or "not existing" filter options?

Unfortunately I don't understand the code behind. PHP is some sort of language, I'm not able to learn. Otherwise I would help in development. So I just can help testing it.

Best Regards.

**Comment by schoenid** [comment]
Another example:

I've got two views as pages.
Basic configuration is:

FORMAT
Grid / Fields

FIELDS
- Content: Image
- Content: Title
- Content: Body

FILTER CRITERIA
- Content: Published (Yes)
- Content: Type (= Book)

So the Difference between Pages is:

**Page 1** --> Displays all books with regular menu field entry

PAGE SETTINGS
- Path: /regular_books
- Menu: Normal: Regular Books

FILTER CRITERIA
- Menu: Parent (> 0)

**Page 2** --> Should display all other books, wich do NOT have a regular menu field entry

PAGE SETTINGS
- Path: /other_books
- Menu: Normal: Other Books

FILTER CRITERIA
- ??? --> Here a filter must be defined, which allows only to display content, which has no regular menu defined, which means, the menu field on the content form is left empty.

**Comment by schoenid** [comment]
Dear  @VasasA

Now I found a solution with the [Views Conditional](https://raspy/backdrop/admin/installer/project/views_conditional) module.

So I could configure the Views Fields as follows:

FIELDS
- Content: Image [hidden]
- Content: Title [hidden]
- Content: Body [hidden]
- Menu: Parent (Parent) [hidden]
- Views: Views Conditional (If p1 is Empty , output [field_images] [title] [body], else output )

This works in the settings of the "Views Conditional" field by defininig 
**If this field...** --> "[p1]==Menu:Parent" **Is...** --> "Empty"
**Then output this...**
- [field_images]<br>
- [title]<br>
- [body]<br>
**Otherwise, output this...** --> ""

This does exactly, what I meant above.
It's maybe not straight forward, but it works perfectly.

So I can now use your standard filters. If you still want to create a specific filter for this purpose, I would surely use your one, because of a more logical way, to use a regular filter, to stripe out the other content.

Many thanks!

**Comment by VasasA** [comment]
@schoenid Thank You for the examples and the detailed descriptions. :+1: 
I thought about it a lot, finally I created a new branch: [content_without_menu_filter](https://github.com/backdrop-contrib/menu_node_views/tree/content_without_menu_filter)
This version contains the new "Content: Content without menu entry" filter. Please test this: [Download](https://github.com/backdrop-contrib/menu_node_views/archive/refs/heads/content_without_menu_filter.zip)

**Comment by schoenid** [comment]
Dear @VasasA 

Thank you a lot, it is working perfectly 👍👍👍

I've tried in on 2 separate Backdrop installations.

So I can now use an easy way for fields:

FIELDS
- Content: Image
- Content: Title
- Content: Body

With filters - for content with menus

FILTER CRITERIA
- Content: Published (Yes)
- Content: Type (= Group)
- Menu: Menu name (longer than 0)

PAGE SETTINGS
- Path: /groups
- Menu: Normal: Main Groups

With filters - for content **without** menus

FILTER CRITERIA
- Content: Published (Yes)
- Content: Type (= Group)
- **Content: Content without menu entry (= )**

PAGE SETTINGS
- Path: /groups2
- Menu: Normal: Other Groups

So I've got two pages, one for groups with a regular menu entry, and one for all the other groups.
A group is a content type, using the organic groups module.
The reason to separate groups: every user on this sites is allowed to create groups, but only users with special permissions are allowed to create a menu entry for it. So It can be differentiated between important groups and the others.

This filter makes much more sense, than the Views Conditional version. It is straight forward with a regular use of filters. 👍
